name: Production Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/geminicare:latest

      - name: Upload application files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml .env"  # Sesuaikan dengan file yang perlu di-upload
          target: "/home/***/ecs-user/geminicare"  # Sesuaikan dengan target directory di server

      - name: Deploy to server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Cek direktori sebelum berpindah
            echo "Current Directory:"
            pwd
            echo "Contents of the directory:"
            ls
            
            cd ecs-user/geminicare || { echo "Directory not found"; exit 1; }
            echo "Changed to directory: $(pwd)"
            ls # Memastikan bahwa kita berada di direktori yang benar dan memeriksa berkas yang ada
            
            # Menjalankan perintah Docker Compose
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d --build
            docker image prune -f
